name: youwallet
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter


#  web3dart:
#    git: git://github.com/simolus3/web3dart.git
  web3dart: ^2.3.3
  bip39: ^1.0.6
  ed25519_hd_key: ^2.2.0
  bitcoin_flutter: ^2.0.2
  flutter_aes_ecb_pkcs5: ^0.1.2
  sacco: ^0.2.0
  steel_crypt: ^3.0.0+1

  decimal: ^2.2.0
  hex: ^0.2.0

  cupertino_icons: ^1.0.4



  image_picker_saver: ^0.3.0
  http: ^0.13.4
  local_auth: ^2.1.0
  share: ^2.0.4

  barcode_scan: ^3.0.1
  shared_preferences: ^2.0.15

  sqflite: ^2.0.2+1
  path_provider: ^2.0.10
  dart_sql: ^0.0.7
  provider: ^6.0.3
  event_bus: ^2.0.0
  get_it: ^7.2.0
  qr_flutter: ^4.0.0
  common_utils: ^2.1.0

  url_launcher: ^6.1.2
  groovin_material_icons: ^1.1.6
  fluttertoast: ^8.0.9
  flutter_slidable: ^1.3.0
  dio: ^4.0.6

  flutter_bugly: ^0.4.4
  flutter_spinkit: ^5.1.0
  html: ^0.15.0
dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  pointycastle: ^3.6.0
  bech32: ^0.2.0
  hex: ^0.2.0
  fixnum: ^1.0.0
  collection: ^1.16.0
  code_builder: ^4.0.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - locale/i18n_en.json
    - locale/i18n_zh.json
    - locale/i18n_ja.json
    - assets/images/logo.png
    - assets/images/home.png
    - assets/images/home-active.png
    - assets/images/icon.png
    - TempMatch.json
    - images/new_wallet.png
    - images/fingerprint.png
    - images/tab_wallet_active.png
    - images/tab_wallet.png
    - images/tab_exchange_active.png
    - images/tab_exchange.png
    - images/tab_receive_active.png
    - images/tab_receive.png
    - images/tab_transfer_active.png
    - images/tab_transfer.png
    - images/qrcode.png
    - images/backup.png
    - images/icon.png
    - images/qrcode.jpeg
    - images/homebk.png
    - images/homebk-full.png
    - images/splash.jpeg
    - images/empty.png
    - images/logo.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  fonts:
    - family: iconfont
      fonts:
        - asset: fonts/iconfont.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
